import { TirPmAutocompleteStyleVars } from 'tir-pm-autocomplete';
import { TirPmButtonStyleVars } from 'tir-pm-button';
import { TirPmCheckboxStyleVars } from 'tir-pm-checkbox';
import { TirPmColorPaletteVars } from 'tir-pm-color-palette';
import { TirPmContextMenuVars } from 'tir-pm-context-menu';
import { TirPmCropFormVars } from 'tir-pm-crop-form';
import { TirCropperVarsModel } from 'tir-pm-cropper';
import { TirPmDatepickerStyleVars } from 'tir-pm-datepicker';
import { TirPmDividerStyleVars } from 'tir-pm-divider';
import { TirPmDrawerVars } from 'tir-pm-drawer';
import { TirPmDropdownStyleVars } from 'tir-pm-dropdown';
import { TirPmFilePreviewStyleVars } from 'tir-pm-file-preview';
import { TirPmFoldPanelStyleVars } from 'tir-pm-fold-panel';
import { TirPmIconPickerStyleVars } from 'tir-pm-icon-picker';
import { TirPmIconViewStyleVars } from 'tir-pm-icon-view';
import { TirPmIndicatorStyleVars } from 'tir-pm-indicator';
import { TirPmInputStyleVars } from 'tir-pm-input';
import { TirPmMenuLayoutStyleVars } from 'tir-pm-menu-layout';
import { TirPmModalStyleVars } from 'tir-pm-modal';
import { TirPmMultiselectStyleVars } from 'tir-pm-multiselect';
import { TirPmNotificationStyleVars } from 'tir-pm-notification';
import { TirPmOptionListStyleVars } from 'tir-pm-option-list';
import { TirPmPaginationStyleVars } from 'tir-pm-pagination';
import { TirPmPlateStyleVars } from 'tir-pm-plate';
import { TirPmPopoverStyleVars } from 'tir-pm-popover';
import { TirPmRadioStyleVars } from 'tir-pm-radio';
import { TirPmResizablePanelStyleVars } from 'tir-pm-resizable-panel';
import { TirPmScrollbarStyleVars } from 'tir-pm-scrollbar';
import { TirPmSearchInputStyleVars } from 'tir-pm-search-input';
import { TirPmSegmentControlStyleVars } from 'tir-pm-segment-control';
import { TirPmSelectStyleVars } from 'tir-pm-select';
import { TirPmSelectBadgeStyleVars } from 'tir-pm-select-badge';
import { TirPmSidebarStyleVars } from 'tir-pm-sidebar';
import { TirPmSkeletonLoaderStyleVars } from 'tir-pm-skeleton-loader';
import { TirPmSliderStyleVars } from 'tir-pm-slider';
import { TirPmSpinnerStyleVars } from 'tir-pm-spinner';
import { TirPmSplitterStyleVars } from 'tir-pm-splitter';
import { TirPmStatusStyleVars } from 'tir-pm-status';
import { TirPmStatusBudgeStyleVars } from 'tir-pm-status-budge';
import { TirPmSvgStyleVars } from 'tir-pm-svg';
import { TirPmSystemMessageStyleVars } from 'tir-pm-system-message';
import { TirPmTableStyleVars } from 'tir-pm-table';
import { TirPmTabsStyleVars } from 'tir-pm-tabs';
import { TirPmTagStyleVars } from 'tir-pm-tag';
import { TirPmTextareaStyleVars } from 'tir-pm-textarea';
import { TirPmTextEditorFileStyleVars } from 'tir-pm-texteditor-file';
import { TirPmToastStyleVars } from 'tir-pm-toast';
import { TirPmToggleStyleVars } from 'tir-pm-toggle-button';
import { TirPmTooltipElementStyleVars } from 'tir-pm-tooltip-element';
import { TirPmVideoPlayerStyleVars } from 'tir-pm-video-player';

export const initStyleVars = () => {
  TirCropperVarsModel.setVars(new TirCropperVarsModel());
  TirPmDatepickerStyleVars.setVars(new TirPmDatepickerStyleVars());
  TirPmSvgStyleVars.setVars(new TirPmSvgStyleVars());
  TirPmResizablePanelStyleVars.setVars(new TirPmResizablePanelStyleVars());
  TirPmMenuLayoutStyleVars.setVars(new TirPmMenuLayoutStyleVars());
  TirPmSkeletonLoaderStyleVars.setVars(new TirPmSkeletonLoaderStyleVars());
  TirPmTooltipElementStyleVars.setVars(new TirPmTooltipElementStyleVars());
  TirPmPopoverStyleVars.setVars(new TirPmPopoverStyleVars());
  TirPmSidebarStyleVars.setVars(new TirPmSidebarStyleVars());
  TirPmOptionListStyleVars.setVars(new TirPmOptionListStyleVars());
  TirPmTabsStyleVars.setVars(new TirPmTabsStyleVars());
  TirPmTagStyleVars.setVars(new TirPmTagStyleVars());
  TirPmIconPickerStyleVars.setVars(new TirPmIconPickerStyleVars());
  TirPmInputStyleVars.setVars(new TirPmInputStyleVars());
  TirPmModalStyleVars.setVars(new TirPmModalStyleVars());
  TirPmCropFormVars.setVars(new TirPmCropFormVars());
  TirPmContextMenuVars.setVars(new TirPmContextMenuVars());
  TirPmDrawerVars.setVars(new TirPmDrawerVars());
  TirPmButtonStyleVars.setVars(new TirPmButtonStyleVars());
  TirPmCheckboxStyleVars.setVars(new TirPmCheckboxStyleVars());
  TirPmColorPaletteVars.setVars(new TirPmColorPaletteVars());
  TirPmRadioStyleVars.setVars(new TirPmRadioStyleVars());
  TirPmScrollbarStyleVars.setVars(new TirPmScrollbarStyleVars());
  TirPmSearchInputStyleVars.setVars(new TirPmSearchInputStyleVars());
  TirPmDividerStyleVars.setVars(new TirPmDividerStyleVars());
  TirPmDropdownStyleVars.setVars(new TirPmDropdownStyleVars());
  TirPmFilePreviewStyleVars.setVars(new TirPmFilePreviewStyleVars());
  TirPmStatusStyleVars.setVars(new TirPmStatusStyleVars());
  TirPmStatusBudgeStyleVars.setVars(new TirPmStatusBudgeStyleVars());
  TirPmTableStyleVars.setVars(new TirPmTableStyleVars());
  TirPmSpinnerStyleVars.setVars(new TirPmSpinnerStyleVars());
  TirPmSegmentControlStyleVars.setVars(new TirPmSegmentControlStyleVars());
  TirPmSystemMessageStyleVars.setVars(new TirPmSystemMessageStyleVars());
  TirPmPlateStyleVars.setVars(new TirPmPlateStyleVars());
  TirPmIndicatorStyleVars.setVars(new TirPmIndicatorStyleVars());
  TirPmIconViewStyleVars.setVars(new TirPmIconViewStyleVars());
  TirPmMultiselectStyleVars.setVars(new TirPmMultiselectStyleVars());
  TirPmPaginationStyleVars.setVars(new TirPmPaginationStyleVars());
  TirPmNotificationStyleVars.setVars(new TirPmNotificationStyleVars());
  TirPmNotificationStyleVars.setVars(new TirPmNotificationStyleVars());
  TirPmAutocompleteStyleVars.setVars(new TirPmAutocompleteStyleVars());
  TirPmFoldPanelStyleVars.setVars(new TirPmFoldPanelStyleVars());
  TirPmVideoPlayerStyleVars.setVars(new TirPmVideoPlayerStyleVars());
  TirPmToggleStyleVars.setVars(new TirPmToggleStyleVars());
  TirPmTextareaStyleVars.setVars(new TirPmTextareaStyleVars());
  TirPmTextEditorFileStyleVars.setVars(new TirPmTextEditorFileStyleVars());
  TirPmToastStyleVars.setVars(new TirPmToastStyleVars());
  TirPmSelectStyleVars.setVars(new TirPmSelectStyleVars());
  TirPmSelectBadgeStyleVars.setVars(new TirPmSelectBadgeStyleVars());
  TirPmSliderStyleVars.setVars(new TirPmSliderStyleVars());
  TirPmSplitterStyleVars.setVars(new TirPmSplitterStyleVars());
};
